export const initialFeeState = {
  admissionFee: "",
  tuitionFee: "",
  cardFee: "",
  libraryFee: "",
  laboratoryFee: "",
  laboratoryBreakage: "",
  librarySecurityFee: "",
  securityFee: "",
  examinationFee: "",
  welfareFee: "",
  hospitalFee: "",
  enrollmentFee: "",
  verificationFee: "",
  reAdmissionFee: "",
  specialFee: "",
  utilityFee: "",
  hostelFee: "",
  prospectusFee: "",
  magazineFee: "",
  donationFee: "",
  loanFee: "",
  fineFee: "",
  miscFee: "",
};
